// app/HeroCarousel.tsx
"use client";

import { useCallback, useEffect, useState } from "react";

const slides = [
  {
    image: "/samlong-hero.png",
    className: "slide-launch",
    eyebrow: "RA MẮT 2026",
    title: <>TƯƠNG LAI<br /><em>DI CHUYỂN</em></>,
    label: "F25 Sport launch",
  },
  {
    image: "/og.png",
    className: "slide-performance",
    eyebrow: "SAM.LOONG F25 SPORT",
    title: <>BỨT PHÁ<br /><em>GIỚI HẠN</em></>,
    label: "F25 Sport performance",
  },
  {
    image: "/samlong-products.png",
    className: "slide-city",
    eyebrow: "NĂNG LƯỢNG XANH",
    title: <>CHẤT RIÊNG<br /><em>ĐÔ THỊ</em></>,
    label: "Sam.Loong urban electric scooters",
  },
];

export function HeroCarousel() {
  const [active, setActive] = useState(0);
  const [paused, setPaused] = useState(false);

  const changeSlide = useCallback((direction: number) => {
    setActive((current) => (current + direction + slides.length) % slides.length);
  }, []);

  useEffect(() => {
    if (paused) return;
    const timer = window.setInterval(() => changeSlide(1), 5500);
    return () => window.clearInterval(timer);
  }, [changeSlide, paused]);

  return (
    <section
      className="hero"
      aria-roledescription="carousel"
      aria-label="Sam.Loong featured vehicles"
      onMouseEnter={() => setPaused(true)}
      onMouseLeave={() => setPaused(false)}
      onFocus={() => setPaused(true)}
      onBlur={(event) => {
        if (!event.currentTarget.contains(event.relatedTarget)) setPaused(false);
      }}
      onKeyDown={(event) => {
        if (event.key === "ArrowLeft") changeSlide(-1);
        if (event.key === "ArrowRight") changeSlide(1);
      }}
    >
      <div className="hero-track" style={{ transform: `translateX(-${active * 100}%)` }}>
        {slides.map((slide, index) => (
          <article
            className={`hero-slide ${slide.className}`}
            key={slide.label}
            aria-hidden={index !== active}
            aria-label={`${index + 1} of ${slides.length}: ${slide.label}`}
          >
            <div className="hero-media" style={{ backgroundImage: `url('${slide.image}')` }} />
            <div className="hero-shade" />
            <div className="hero-copy">
              <span>{slide.eyebrow}</span>
              <h1>{slide.title}</h1>
              <a href="#models" tabIndex={index === active ? 0 : -1}>KHÁM PHÁ NGAY</a>
            </div>
          </article>
        ))}
      </div>
      <button className="hero-arrow left" onClick={() => changeSlide(-1)} aria-label="Previous slide">‹</button>
      <button className="hero-arrow right" onClick={() => changeSlide(1)} aria-label="Next slide">›</button>
      <div className="hero-dots" aria-label={`Slide ${active + 1} of ${slides.length}`}>
        {slides.map((slide, index) => (
          <button
            key={slide.label}
            className={index === active ? "active" : ""}
            onClick={() => setActive(index)}
            aria-label={`Show slide ${index + 1}`}
            aria-current={index === active ? "true" : undefined}
          />
        ))}
      </div>
    </section>
  );
}

// web/components/HeroCarousel.vue
<script setup lang="ts">
type Slide = { id: number; title: string; subtitle?: string; eyebrow?: string; imageUrl: string; linkUrl?: string }
const props = defineProps<{ slides: Slide[] }>()
const active = ref(0)
const paused = ref(false)
let timer: ReturnType<typeof setInterval> | undefined
const change = (step: number) => { if (props.slides.length) active.value = (active.value + step + props.slides.length) % props.slides.length }
const start = () => { if (!paused.value && props.slides.length > 1) timer = setInterval(() => change(1), 5500) }
const stop = () => { if (timer) clearInterval(timer) }
watch(paused, () => { stop(); start() })
watch(() => props.slides.length, () => { active.value = 0; stop(); start() })
onMounted(start)
onBeforeUnmount(stop)
</script>

<template>
  <section v-if="slides.length" class="hero" aria-roledescription="carousel" aria-label="Sam.Loong featured vehicles" @mouseenter="paused = true" @mouseleave="paused = false" @focusin="paused = true" @focusout="paused = false" @keydown.left="change(-1)" @keydown.right="change(1)">
    <div class="hero-track" :style="{ transform: `translateX(-${active * 100}%)` }">
      <article v-for="(slide, index) in slides" :key="slide.id" class="hero-slide" :aria-hidden="index !== active">
        <div class="hero-media" :style="{ backgroundImage: `url('${slide.imageUrl}')` }" />
        <div class="hero-shade" />
        <div class="hero-copy"><span>{{ slide.eyebrow }}</span><h1>{{ slide.title }}<br><em>{{ slide.subtitle }}</em></h1><a :href="slide.linkUrl || '#models'" :tabindex="index === active ? 0 : -1">KHÁM PHÁ NGAY</a></div>
      </article>
    </div>
    <button v-if="slides.length > 1" class="hero-arrow left" aria-label="Previous slide" @click="change(-1)">‹</button>
    <button v-if="slides.length > 1" class="hero-arrow right" aria-label="Next slide" @click="change(1)">›</button>
    <div v-if="slides.length > 1" class="hero-dots" :aria-label="`Slide ${active + 1} of ${slides.length}`"><button v-for="(_, index) in slides" :key="index" :class="{ active: index === active }" :aria-label="`Show slide ${index + 1}`" @click="active = index" /></div>
  </section>
</template>
